### ISSUE TITLE
cannot find function `unlock` in module `os`

### ISSUE THREAD

**Issue by slyons** [fermyon/wasi-experimental-toolkit#14]
I'm trying to build a simple interface (for [environment variables](https://github.com/slyons/wasi-experimental-toolkit/tree/feature/env_vars), as an experiment) and I'm running into this stack trace after adding my module to `build.rs`

```
   Compiling cranelift-codegen v0.80.0
   Compiling quote v1.0.15
   Compiling memoffset v0.6.5
   Compiling generic-array v0.14.5
   Compiling region v2.2.0
   Compiling cc v1.0.72
   Compiling regex v1.5.4
   Compiling pulldown-cmark v0.8.0
   Compiling rand_chacha v0.3.1
   Compiling miniz_oxide v0.4.4
   Compiling rustix v0.31.3
   Compiling wat v1.0.41
   Compiling crossbeam-epoch v0.9.6
error[E0425]: cannot find function `lock` in module `os`
  --> /Users/slyons/.cargo/registry/src/github.com-1ecc6299db9ec823/region-2.2.0/src/lock.rs:30:7
   |
30 |   os::lock(
   |       ^^^^ not found in `os`
   |
help: consider importing this function
   |
1  | use lock;
   |

error[E0425]: cannot find function `unlock` in module `os`
  --> /Users/slyons/.cargo/registry/src/github.com-1ecc6299db9ec823/region-2.2.0/src/lock.rs:60:7
   |
60 |   os::unlock(
   |       ^^^^^^ not found in `os`
   |
help: consider importing this function
   |
1  | use unlock;
   |

error[E0425]: cannot find function `page_size` in module `os`
  --> /Users/slyons/.cargo/registry/src/github.com-1ecc6299db9ec823/region-2.2.0/src/page.rs:16:39
   |
16 |     INIT.call_once(|| PAGE_SIZE = os::page_size());
   |                                       ^^^^^^^^^ not found in `os`

error[E0425]: cannot find function `set_protection` in module `os`
  --> /Users/slyons/.cargo/registry/src/github.com-1ecc6299db9ec823/region-2.2.0/src/protect.rs:48:7
   |
48 |   os::set_protection(
   |       ^^^^^^^^^^^^^^ not found in `os`

error[E0425]: cannot find function `get_region` in module `os`
   --> /Users/slyons/.cargo/registry/src/github.com-1ecc6299db9ec823/region-2.2.0/src/lib.rs:133:7
    |
133 |   os::get_region(page::floor(address as usize) as *const u8)
    |       ^^^^^^^^^^ not found in `os`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `region` due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I must admit this is my first foray into the WASI SDK/toolkit so I'd appreciate any advice.

**Comment by radu-matei** [comment]
Ok, first things first.
`crates/envvars` is a _host_ implementation that uses Wasmtime — this will not compile to `wasm32-wasi`, as it needs to be compiled for the actual host platform  — so it doesn't need to be compiled with `cargo build --target wasm32-wasi`.
If you added it to `Cargo.toml`, then it should be compiled, and the test you added should be run regularly.

This should solve your compilation issue.


The second aspect to talk about here is that WASI explicitly requires selecting the environment variables that are exposed into the module at runtime — so a "pass-through" style interface would end up exposing everything to the guest module, which might not be ideal.

**Comment by slyons** [comment]
Thanks for the reply! 

I had honestly not yet looked at the WASI spec, I was more doing this to figure out how to structure everything before I tackle a module for Secrets. I'll add the filter to select what is exposed, then!

**Comment by radu-matei** [comment]
Awesome, let me know if you hit any more compilation issues, happy to help.


Closing for now, but feel free to reopen here, or a new issue.
