### ISSUE TITLE
Implement logging interface

### ISSUE THREAD

**Issue by radu-matei** [fermyon/wasi-experimental-toolkit#2]
There are now a few examples for both host and guest implementations for an interface, so implementing the current logging interface _should_ be straightforward.

**Comment by nitishm** [comment]
I can take this up. Any particular interface that we are trying to implement?

**Comment by radu-matei** [comment]
Sorry about that, should have linked the interface in the first place — https://github.com/fermyon/wasi-experimental-toolkit/blob/main/wit/ephemeral/wasi-log.wit
